"""
Configuration package for AI-Powered Job Recommendation System
"""

from .config import (
    PROJECT_ROOT,
    DATA_DIR,
    RAW_DATA_DIR,
    PROCESSED_DATA_DIR,
    MODELS_DIR,
    RESULTS_DIR,
    JOBS_CSV_PATH,
    RESUMES_CSV_PATH,
    PROCESSED_JOBS_PATH,
    PROCESSED_RESUMES_PATH,
    TRAIN_DATA_PATH,
    TEST_DATA_PATH,
    MODEL_PATH,
    DATA_CLEANING_CONFIG,
    FEATURE_ENGINEERING_CONFIG,
    MODEL_CONFIG,
    EVALUATION_CONFIG,
    STREAMLIT_CONFIG,
)

__all__ = [
    'PROJECT_ROOT',
    'DATA_DIR',
    'RAW_DATA_DIR',
    'PROCESSED_DATA_DIR',
    'MODELS_DIR',
    'RESULTS_DIR',
    'JOBS_CSV_PATH',
    'RESUMES_CSV_PATH',
    'PROCESSED_JOBS_PATH',
    'PROCESSED_RESUMES_PATH',
    'TRAIN_DATA_PATH',
    'TEST_DATA_PATH',
    'MODEL_PATH',
    'DATA_CLEANING_CONFIG',
    'FEATURE_ENGINEERING_CONFIG',
    'MODEL_CONFIG',
    'EVALUATION_CONFIG',
    'STREAMLIT_CONFIG',
]
